team-zumba/nagano-cake

- app/views/layouts/application.html.erb
> conflict practice

- config/environments/development.rb
- db/seeds.rb
- seedファイル修正
- config/environments/development.rbに、SQLite3を同期処理に変更するコードを記述
> Bugfix k seed

- app/controllers/application_controller.rb
- app/views/admin/sessions/new.html.erb
- app/views/layouts/_flash.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
> Feature k admin sessions

- app/controllers/public/cart_items_controller.rb
- app/controllers/public/items_controller.rb
- app/models/item.rb
- app/views/public/items/index.html.erb
- app/views/public/items/show.html.erb
cart-items controllerを作成し、createとindexを定義して、createにredirect
itemsの数量のフォームをform_withに変更
cart_itemsのviewフォルダを追加
items index viewの真ん中にcol-1を追加/サイドテーブル内容を削除
items indexのviewにmargin top/bottomを追加
Itemモデルに税込価格計算用の定義
items controllerのindexに@genres定義を追記
itemのindex 商品詳細右側viewページレイアウトを修正
items indexのviewレイアウトを修正
> Feature m public items

- app/controllers/public/cart_items_controller.rb
- app/views/public/genres/_list.erb
- app/views/public/items/_list.html.erb
- app/views/public/items/show.html.erb
- config/routes.rb
publicコントローラーのURLの頭の「public」を削除
> publicコントローラーのURLを修正

- app/controllers/public/customers_controller.rb
- app/controllers/public/sessions_controller.rb
- app/models/customer.rb
- app/views/public/customers/check.html.erb
- app/views/public/customers/show.html.erb
- app/views/public/items/show.html.erb
- config/routes.rb
> Feature m public customers

- app/views/layouts/application.html.erb
- app/views/public/sessions/new.html.erb
- app/views/public/shared/_links.html.erb
- config/routes.rb
- db/seeds.rb
> Feature d public sessions

- app/controllers/admin/items_controller.rb
- app/views/admin/items/edit.html.erb
- app/views/admin/items/new.html.erb
> admin items を修正

- app/controllers/application_controller.rb
- app/controllers/public/addresses_controller.rb
- app/controllers/public/cart_items_controller.rb
- app/controllers/public/customers_controller.rb
- app/controllers/public/orders_controller.rb
- config/routes.rb
非ログイン時に、顧客マイページなどに移動するとエラーが発生する点の修正
> 非ログイン時のページアクセス制限

- app/controllers/admin/homes_controller.rb
- app/models/order.rb
- app/models/order_detail.rb
- app/views/admin/homes/index.html.erb
- config/application.rb
- config/locales/ja.yml
- config/routes.rb
> Feature m admin homes

- Gemfile
- Gemfile.lock
- app/controllers/public/orders_controller.rb
- app/models/address.rb
- app/models/cart_item.rb
- app/models/customer.rb
- app/models/genre.rb
- app/models/item.rb
- app/models/order.rb
- app/models/order_detail.rb
- app/views/public/orders/check.html.erb
- app/views/public/orders/complete.html.erb
- app/views/public/orders/index.html.erb
- app/views/public/orders/new.html.erb
- app/views/public/orders/show.html.erb
- config/routes.rb
- s
- 注文情報入力画面
- 注文確認画面
- 注文確定画面
- 注文履歴一覧
- 注文履歴詳細
> Feature d public orders

- app/assets/stylesheets/public/homes.scss
- app/javascript/homes/top.js
- app/views/admin/customers/edit.html.erb
- app/views/admin/customers/index.html.erb
- app/views/admin/customers/show.html.erb
- app/views/admin/genres/edit.html.erb
- app/views/admin/genres/index.html.erb
- app/views/admin/sessions/new.html.erb
- app/views/public/cart_items/index.html.erb
- app/views/public/genres/_search-box.erb
- app/views/public/homes/top.html.erb
- app/views/public/items/index.html.erb
- app/views/public/items/show.html.erb
- config/routes.rb
- db/seeds.rb
- 管理者
- ログインページ
- 会員
- 一覧ページ
- 詳細ページ
- 編集ページ
- ジャンル
- 一覧・追加ページ
- 編集ページ
- 顧客
- トップページ
- カートページ
- 商品一覧
- 商品詳細
> 各ページのスタイルを整える

- app/controllers/public/orders_controller.rb
- app/views/public/orders/check.html.erb
- app/views/public/orders/new.html.erb
- app/views/public/orders/show.html.erb
- 注文確認画面のエラー訂正
- 注文履歴詳細画面の価格表示訂正
- 支払い方法選択のラジオボタン修正
> [Add]注文画面のバグ修正

- app/controllers/public/addresses_controller.rb
- app/views/public/addresses/edit.html.erb
- app/views/public/addresses/index.html.erb
- 配送先登録/一覧
- 配送先編集画面
- 配送先更新機能
- 配送先削除機能
> Feature d public addresses

- app/controllers/admin/orders_controller.rb
- app/controllers/public/customers_controller.rb
- app/models/item.rb
- app/models/order.rb
- app/models/order_detail.rb
- app/views/admin/homes/index.html.erb
- app/views/admin/orders/customer_index.html.erb
- app/views/admin/orders/show.html.erb
- app/views/public/customers/edit.html.erb
- config/locales/ja.yml
- config/routes.rb
admin orders関連の機能完了しました！
プルリク承認お願いします。
> Feature m admin orders

- app/controllers/admin/items_controller.rb
- app/controllers/public/items_controller.rb
- app/views/admin/items/index.html.erb
- app/views/public/items/_list.html.erb
paginationの設定をしました。プルリク承認お願いします〜
> [Add]paginationを追加

- app/controllers/application_controller.rb
- app/controllers/public/registrations_controller.rb
- app/views/layouts/application.html.erb
- app/views/public/items/_list.html.erb
- app/views/public/items/show.html.erb
- app/views/public/orders/check.html.erb
> Feature m pagination

- app/views/public/cart_items/index.html.erb
> [Fix]買い物を続けるのリンク先をトップページに変更

- app/controllers/public/addresses_controller.rb
- app/models/address.rb
- app/views/public/addresses/index.html.erb
> [Add]配送先登録画面バリデーション追加

- app/controllers/admin/order_details_controller.rb
> [Add]製作ステータス修正

- app/controllers/admin/order_details_controller.rb
> [Fix]制作ステータスと注文ステータスの連動（製作中）
